server:
  port: 8080
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: jobportal-api
  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: ${MONGODB_URI}
      #      uri: mongodb://localhost:27017
      database: ${MONGODB_DATABASE}

  jackson:
    time-zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

jwt:
  signerkey: ${SIGNER_KEY}
  valid-duration: ${VALID_DURATION} # in HOURS
  refreshable-duration: ${REFRESHABLE_DURATION} # in HOURS

cors:
  allowed:
    origins: ${FRONTEND_URL}
