server:
  port: 8080
  servlet:
    context-path: "/api/v0"

spring:
  application:
    name: jobportal-api
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 9
      minimum-idle: 5
      connection-timeout: 10000
      idle-timeout: 300000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerkey: ${SIGNER_KEY}
  valid-duration: ${VALID_DURATION} # in HOURS
  refreshable-duration: ${REFRESHABLE_DURATION} # in HOURS

cors:
  allowed:
    origins: ${FRONTEND_URL}
